server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/j2eecombined?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&nullCatalogMeansCurrent=true
    username: root
    password: zucc
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: com/example/demo/mapper/xml/*.xml
#  config-location: classpath:mybatis_config.xml
#  mybatis.config-location=classpath:mybatis/mybatis-config.xml
#  mybatis.mapper-locations=classpath:mybatis/mapper/*.xml
logging:
  level:
    root: debug