server:
  port: 8088

mybatis:
  config-locations: classpath:mybatis_config.xml
  mapper-locations: classpath:com/example/demo/mapper/xml/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.example.entity  # 注意：对应实体类的路径
